### ISSUE TITLE
The App code is not working

### ISSUE THREAD

**Issue by techvenky** [OfficeDev/Office-Apps#8]
The App code is not working. Code has Wikipedia_dev.js reference but its not in the files.

**Comment by Rick-Kirkham** [comment]
Sorry it took so long to respond. The file you mention is not in the files because it is generated. Note this sentence from the Readme file: 
"All the .js files started with Wikipedia_ will be compiled as one file Wikipedia_dev.js in the same folder when you start running. You can see it after clicking 'Show All Files'."
